stages:
    - lint

lint:typoscriptcgl:
    image: composer:2.1.3
    stage: lint
    script:
        - composer global require helmich/typo3-typoscript-lint
        - /tmp/vendor/bin/typoscript-lint Configuration/*.typoscript

lint:yaml:
    image: python:alpine3.7
    stage: lint
    before_script:
        - pip install yamllint==1.10.0
    script:
        - yamllint -c yamllint.yaml localPackages/ yamllint.yaml .gitlab-ci.yml tslint.yaml
