---
stages:
  - build
  - lint

build:
  stage: build
  image: composer:2.1.3
  before_script:
    - apk add bash --no-cache
    - apk add git --update
  script:
    - composer install --no-progress --no-ansi --no-interaction
    - ls -al
  artifacts:
    name: typo3
    paths:
      - .Build/vendor/
      - ./composer.json
    expire_in: '1h'

typoscript:
  dependencies:
    - build
  image: composer:2.1.3
  stage: lint
  script:
    - composer require --dev helmich/typo3-typoscript-lint
    - ls -al .Build
    - .Build/bin/typoscript-lint

yaml:
  image: python:alpine3.7
  stage: lint
  before_script:
    - pip install yamllint==1.10.0
  script:
    - pwd
    - ls -al
    - yamllint -c .yamllint .

sql:
  dependencies:
    - build
  image: composer:2.1.3
  stage: lint
  script:
    - composer require --dev liquipedia/sqllint
    - .Build/bin/sqllint
