stages:
    - lint

lint:typoscriptcgl:
    image: composer:2.1.3
    stage: lint
    before_script:
        - git clone https://christian.knell:$gitlab_token@git.knell.it/typo3/sportms/sportms.git /tmp/tx_ext
    script:
        - composer global require helmich/typo3-typoscript-lint
        - /tmp/vendor/bin/typoscript-lint /tmp/tx_ext/Configuration/*.typoscript

lint:yaml:
    image: python:alpine3.7
    stage: lint
    before_script:
        - pip install yamllint==1.10.0
    script:
        - yamllint -c yamllint.yaml localPackages/ yamllint.yaml .gitlab-ci.yml tslint.yaml
