---
stages:
  - build
  - lint

build:
  stage: build
  image: composer:2.1.3
  before_script:
    - apk add bash --no-cache
    - apk add git --update
  script:
    - composer install --no-progress --no-ansi --no-interaction
    - ls -al
  artifacts:
    name: typo3
    paths:
      - .Build/vendor/
      - ./composer.json
    expire_in: '1h'

fluid:
  dependencies:
    - build
  image: composer:2.1.3
  stage: lint
  script:
    - composer require --dev typo3fluid/fluid-lint:dev-master
    - .Build/bin/fluidline Resoures/Private/.html

sql:
  dependencies:
    - build
  image: composer:2.1.3
  stage: lint
  script:
    - composer require --dev liquipedia/sqllint
    - .Build/bin/sqllint

typoscript:
  dependencies:
    - build
  image: composer:2.1.3
  stage: lint
  script:
    - composer require --dev helmich/typo3-typoscript-lint
    - .Build/bin/typoscript-lint

xliff:
  dependencies:
    - build
  image: composer:2.1.3
  stage: lint
  script:
    - composer require --dev symfony/translation
    - ls -al .Build
    - ls -al .Build/bin
    - ls -al .Build/vendor
    - php .Build/bin/console lint:xliff /Resources/Private/Language

yaml:
  image: python:alpine3.7
  stage: lint
  before_script:
    - pip install yamllint==1.10.0
  script:
    - yamllint -c .yamllint .
