stages:
    - lint

lint:typoscriptcgl:
    image: composer:1.6
    stage: lint
    script:
        - composer install --no-progress --no-ansi --no-interaction
        - ./vendor/bin/typoscript-lint -c tslint.yaml

lint:yaml:
    image: python:alpine3.7
    stage: lint
    before_script:
        - pip install yamllint==1.10.0
    script:
        - yamllint -c yamllint.yaml localPackages/ yamllint.yaml .gitlab-ci.yml tslint.yaml
