stages:
    - build
    - lint

build application with dev dependencies:
    stage: build
    image: composer:2.1.3
    before_script:
        - apk add bash --no-cache
        - apk add git --update
        - git clone https://christian.knell:$gitlab_token@git.knell.it/typo3/sportms/sportms.git .
    script:
        - composer global require hirak/prestissimo
        - composer install --no-progress --no-ansi --no-interaction
    artifacts:
        name: typo3
        paths:
            - ./vendor/
            - ./web/
            - ./composer.json
            - ./composer.lock
        expire_in: '1h'

typoscript:
    image: composer:2.1.3
    stage: lint
    before_script:
        - git clone https://christian.knell:$gitlab_token@git.knell.it/typo3/sportms/sportms.git /tmp/tx_ext
    script:
        - composer require --dev helmich/typo3-typoscript-lint
        - ./vendor/bin/typoscript-lint

yaml:
    image: python:alpine3.7
    stage: lint
    before_script:
        - pip install yamllint==1.10.0
    script:
        - yamllint -c yamllint.yaml localPackages/ yamllint.yaml .gitlab-ci.yml tslint.yaml
