---
extends: default

ignore: |
  .Build/

yaml-files:
    - '*.yaml'
    - '*.yml'
    - '.yamllint'

rules:
    document-start:
        present: true
        level: error
    line-length:
        max: 80
        level: warning
